### ISSUE TITLE
zmypy fails to resolve modules when run from outside mypy_path

### ISSUE THREAD

**Issue by Feuermurmel** [zubanls/zubanls#3]
I have some trouble getting `zmypy` to work within a project setup that has its `mypy_path` not equal to the root of the repository. My repository has the following layout:

```
(venv) $ tree --gitignore
.
├── Makefile
├── pyproject.toml
├── readme.md
└── src
    └── hello_zuban
        ├── __init__.py
        └── hello.py
```

Mypy's `mypy_path` is set up to accomodate this:

```toml
# pyproject.toml
[project]
name = "hello_zuban"
version = "0.1.0"

requires-python = ">= 3.12"
dependencies = []

[project.scripts]
hello-zuban = "hello_zuban:entry_point"

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
strict = true
```

```python
# src/hello_zuban/__init__.py
from hello_zuban.hello import X

x = X()
```

```python
# src/hello_zuban/hello.py
class X:
    pass
```

This works with `mypy`, but `zmypy` seems to be unable to resolve the path of package `hello_zuban.hello`: 

```
(venv) $ mypy src
Success: no issues found in 2 source files
(venv) $ zmypy src
src/hello_zuban/__init__.py:1: error: Cannot find implementation or library stub for module named "hello_zuban"
Found 1 error in 1 file (checked 2 source files)
```

Python 3.13 \
zmypy 0.0.15 \
macOS 14.7.6
